
variables:
  SONAR_TOKEN: $SONAR_TOKEN
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

default:
  image:
    name: cimg/openjdk:11.0-browsers

service-build:
  script:
    - ./gradlew build
    - mkdir -p ./junit/ && find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ./junit/ \;
    - ./gradlew sonarqube -Dsonar.login=$SONAR_TOKEN -Dsonar.branch.name=$CI_COMMIT_BRANCH
    - ./gradlew simulator-core:publish
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    when: on_success
    paths:
      - ./.gradle
  artifacts:
    when: always
    paths:
      - reports
    reports:
      junit: ./junit/TEST-*.xml
