variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

default:
  image:
    name: openjdk:17-jdk-slim

build:
  stage: build
  script:
    - ./gradlew build
    - mkdir -p ./junit/ && find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ./junit/ \;
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    when: on_success
    paths:
      - ./.gradle
      - ./*/build
  artifacts:
    when: always
    paths:
      - reports
    reports:
      junit: ./junit/TEST-*.xml